import { Geist, Geist_Mono } from "next/font/google";
import { ThemeProvider } from 'next-themes';
import '../app/lib/utils/fontawesome';
import "./globals.css";
import Providers from "./ui/components/Providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <Providers attribute="class" defaultTheme="system" enableSystem className="bg-#fafafaff dark:bg-#202c37ff">
        {children}
      </Providers>
      </body>
    </html>
  );
}
